[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "javascriptcore"
version = "0.1.0"

[dependencies]
glib = "^0.1.2"

[dependencies.javascriptcore-sys]
git = "https://github.com/antoyo/javascriptcore-sys-rs"
version = "0.1.0"
