[package]
authors = ["The Gtk-rs Project Developers"]
name = "javascriptcore"
version = "0.1.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "^0.1.3"

[dependencies.javascriptcore-sys]
git = "https://github.com/gtk-rs/javascriptcore-rs"
version = "0.1.0"
