[package]
name = "javascriptcore-rs"
version = "0.2.0"
authors = ["The Gtk-rs Project Developers"]

description = "Rust bindings for the javacriptcore library"
repository = "https://github.com/gtk-rs/javascriptcore-rs"
license = "MIT"
homepage = "http://gtk-rs.org"
keywords = ["javascript", "gtk-rs", "gnome"]

[lib]
name = "javascriptcore"

[dependencies]
glib = "^0.3.0"
javascriptcore-rs-sys = "0.1"
