[package]
name = "javascriptcore"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.javascriptcore-sys]
git = "https://github.com/antoyo/javascriptcore-sys-rs"
version = "0.1.0"
